Module5 task1
htmlacademy-vue/1450419-pizza-1 pull request #5
Opened 2022-05-20 11:03 UTC by kivals

2022-05-21 03:22 UTC, enotke requested changes

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/common/components/AppSheet.vue
> +      <slot name="header-title"></slot>
https://up.htmlacademy.ru/vue/1/criteries#b14

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/common/components/AppTitle.vue
> +    <slot></slot>
https://up.htmlacademy.ru/vue/1/criteries#b14

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/common/helpers/validate.helper.js
> +  isNotEmpty: {
А в чем разница между isNotEmpty и required?

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/modules/cart/components/CartAdditionalList.vue
> +        const count = ~selectedMiscIndex
А для чего тут `~`?

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/modules/cart/components/CartAdditionalList.vue
> +        const count = ~selectedMiscIndex
По идее можно просто 
`return this.selectedMisc.find(selMisc => selMisc.id === miscItem.id)?.count || 0`

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/modules/cart/components/CartDeliveryInfo.vue
> +      this.$emit("change-street", value);
Какое-то прям лишнее переусложнение. В этом компоненте не нужно ничего хранить. Можно же просто в инпуте обрабатывать событие 
` <input type="text" name="house" @input="$emit("change-street", $event)" />`

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/views/Cart.vue
> +            :street="address.street"
Тут можно использовать `:street.sync`

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/views/Cart.vue
> +            :street="address.street"
Чтобы избавиться от `@change-street="address.street = $event"`

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      <AppTitle size="big">Конструктор пиццы</AppTitle>
`size="big"` big можно импортировать из AppTitle

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/views/Cart.vue
> +      return true;
Нужно проверять тип доставки, адрес

2022-05-21 03:22 UTC, enotke commented on src/frontend/src/views/Cart.vue
> +      return true;
![image](https://user-images.githubusercontent.com/88033634/169633499-9d37c6ac-ec2d-46ef-830b-637838d9ffb5.png)

2022-05-21 03:23 UTC, enotke commented
Верстка немного поехала 
![image](https://user-images.githubusercontent.com/88033634/169633553-c001ec16-2597-4e0e-bece-401417213765.png)

2022-05-21 03:23 UTC, enotke commented
![image](https://user-images.githubusercontent.com/88033634/169633571-f6ce075a-accb-4393-9b59-a579a74f1af1.png)
Шапка два раза рендерится

2022-05-26 09:16 UTC, kivals commented on src/frontend/src/common/helpers/validate.helper.js
> +  isNotEmpty: {
копипаста. Убрал лишнее.

2022-05-26 09:24 UTC, kivals commented on src/frontend/src/modules/cart/components/CartAdditionalList.vue
> +        const count = ~selectedMiscIndex
согласен. избыточно.

2022-05-26 12:25 UTC, kivals commented on src/frontend/src/modules/cart/components/CartDeliveryInfo.vue
> +      this.$emit("change-street", value);
Хранил в этом компоненте для того, чтобы можно было очистить поля когда селектор меняется на "заберу сам".
Сделал как ты сказал: состояния убрал, оставил только положение селектора в `data`. И очищаю поля уже в родителе (`Cart.vue`)

2022-05-26 12:48 UTC, kivals commented on src/frontend/src/views/Index.vue
> +      <AppTitle size="big">Конструктор пиццы</AppTitle>
Тут не понял как импортировать из vue файла. Или имелось ввиду из `AppTitle` вынести константу `sizes` в общий `constants.js`?

2022-05-27 01:06 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      <AppTitle size="big">Конструктор пиццы</AppTitle>
Также как и из обычного Js файла. Можно и в constraints вынести

2022-05-27 16:49 UTC, kivals commented on src/frontend/src/views/Index.vue
> +      <AppTitle size="big">Конструктор пиццы</AppTitle>
А как потом вставить в template  `<AppTitle size="big">` ? Создавать data или computed?

2022-05-27 16:50 UTC, kivals commented on src/frontend/src/views/Index.vue
> +      <AppTitle size="big">Конструктор пиццы</AppTitle>
`<AppTitle :size="title.BIG">` - так же вроде нельзя, если просто ипортировать title

2022-05-28 00:25 UTC, merged